
//import java.sql.Connection;
//import java.sql.Connection;
//import com.mysql.cj.x.protobuf.MysqlxDatatypes.Scalar.String;
import java.awt.HeadlessException;
import java.sql.*;
//import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.text.DateFormat;
import java.text.*;
import javax.swing.JTextField;
import static javax.swing.UIManager.getString;

public class welcome_page extends javax.swing.JFrame {
    Date date;
    String datestart;
    /**
     * Creates new form welcome_page
     */
    public welcome_page() {
        initComponents();
        table_update();
        this.setTitle("Miliarya");
         setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderPanel = new javax.swing.JPanel();
        Header = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Panel2 = new javax.swing.JPanel();
        Header2 = new javax.swing.JLabel();
        SerialNo = new javax.swing.JLabel();
        PolicyNo = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        Premium = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        tf5 = new javax.swing.JTextField();
        Mode = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Add = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        tf7 = new javax.swing.JComboBox<>();
        tf6 = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        Search = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        tf8 = new javax.swing.JTextField();
        BSearch = new javax.swing.JButton();
        ShowAll = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        databse = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        HeaderPanel.setBackground(new java.awt.Color(204, 255, 255));
        HeaderPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 102, 102)));

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.setFont(new java.awt.Font("Lucida Calligraphy", 1, 48)); // NOI18N
        Header.setForeground(new java.awt.Color(255, 153, 0));
        Header.setText("Miliarya Management System");
        Header.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 255, 255), new java.awt.Color(102, 255, 255), new java.awt.Color(51, 255, 255), new java.awt.Color(102, 255, 255)));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MiliaryaLOGOM.png"))); // NOI18N

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(Header)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel2.setBackground(new java.awt.Color(204, 204, 204));
        Panel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 255, 51)));

        Header2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 26)); // NOI18N
        Header2.setForeground(new java.awt.Color(255, 255, 255));
        Header2.setText("Manage Policies");

        SerialNo.setFont(new java.awt.Font("Lucida Calligraphy", 1, 17)); // NOI18N
        SerialNo.setForeground(new java.awt.Color(255, 255, 255));
        SerialNo.setText("Serail No.");

        PolicyNo.setFont(new java.awt.Font("Lucida Calligraphy", 1, 17)); // NOI18N
        PolicyNo.setForeground(new java.awt.Color(255, 255, 255));
        PolicyNo.setText("Policy No.");

        Name.setFont(new java.awt.Font("Lucida Calligraphy", 1, 17)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("Name");

        Address.setFont(new java.awt.Font("Lucida Calligraphy", 1, 17)); // NOI18N
        Address.setForeground(new java.awt.Color(255, 255, 255));
        Address.setText("Address");

        Premium.setFont(new java.awt.Font("Lucida Calligraphy", 1, 17)); // NOI18N
        Premium.setForeground(new java.awt.Color(255, 255, 255));
        Premium.setText("Premium");

        Date.setFont(new java.awt.Font("Lucida Calligraphy", 1, 17)); // NOI18N
        Date.setForeground(new java.awt.Color(255, 255, 255));
        Date.setText("Date Start");

        tf1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });

        tf2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153)));
        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });

        tf3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153)));

        tf4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153)));

        tf5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153)));

        Mode.setFont(new java.awt.Font("Lucida Calligraphy", 1, 17)); // NOI18N
        Mode.setForeground(new java.awt.Color(255, 255, 255));
        Mode.setText("Mode");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        Add.setBackground(new java.awt.Color(255, 255, 255));
        Add.setFont(new java.awt.Font("Lucida Calligraphy", 1, 13)); // NOI18N
        Add.setForeground(new java.awt.Color(102, 102, 102));
        Add.setText("Add");
        Add.setBorder(null);
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Update.setBackground(new java.awt.Color(255, 255, 255));
        Update.setFont(new java.awt.Font("Lucida Calligraphy", 1, 13)); // NOI18N
        Update.setForeground(new java.awt.Color(102, 102, 102));
        Update.setText("Clear");
        Update.setBorder(null);
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Clear.setBackground(new java.awt.Color(255, 255, 255));
        Clear.setFont(new java.awt.Font("Lucida Calligraphy", 1, 13)); // NOI18N
        Clear.setForeground(new java.awt.Color(102, 102, 102));
        Clear.setText("Update");
        Clear.setBorder(null);
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        Delete.setBackground(new java.awt.Color(255, 255, 255));
        Delete.setFont(new java.awt.Font("Lucida Calligraphy", 1, 13)); // NOI18N
        Delete.setForeground(new java.awt.Color(102, 102, 102));
        Delete.setText("Delete");
        Delete.setBorder(null);
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Clear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Add, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addComponent(Delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tf7.setFont(new java.awt.Font("Lucida Calligraphy", 1, 13)); // NOI18N
        tf7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Six Months  (06 M)", "One Year    (12 M)" }));
        tf7.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 0), new java.awt.Color(255, 204, 0))));

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(Header2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addComponent(SerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PolicyNo)
                            .addComponent(Address)
                            .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Premium)
                            .addComponent(Date)
                            .addComponent(Mode))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf2, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(tf3)
                            .addComponent(tf4)
                            .addComponent(tf5)
                            .addComponent(tf7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(39, 39, 39))
            .addGroup(Panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addComponent(Header2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SerialNo)
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(PolicyNo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name)
                    .addComponent(tf3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Address)
                    .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Premium)
                    .addComponent(tf5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(Date))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(tf6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mode)
                    .addComponent(tf7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 0, 204)));

        Search.setFont(new java.awt.Font("Lucida Calligraphy", 1, 17)); // NOI18N
        Search.setForeground(new java.awt.Color(255, 255, 255));
        Search.setText("Search By :");

        jComboBox1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "Address", "Policy No." }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        tf8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        tf8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf8ActionPerformed(evt);
            }
        });

        BSearch.setBackground(new java.awt.Color(153, 255, 255));
        BSearch.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        BSearch.setForeground(new java.awt.Color(255, 0, 204));
        BSearch.setText("Search");
        BSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSearchActionPerformed(evt);
            }
        });

        ShowAll.setBackground(new java.awt.Color(153, 255, 255));
        ShowAll.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        ShowAll.setForeground(new java.awt.Color(255, 0, 255));
        ShowAll.setText("Show All");
        ShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowAllActionPerformed(evt);
            }
        });

        databse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr_No.", "Policy_No.", "Name", "Address", "Premium", "Date_Start", "Mode"
            }
        ));
        databse.setGridColor(new java.awt.Color(255, 255, 255));
        databse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                databseMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(databse);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tf8, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(BSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(ShowAll, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addComponent(jScrollPane2)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowAll, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(HeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  
    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void tf8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf8ActionPerformed

    private void ShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowAllActionPerformed
       table_update();
    }//GEN-LAST:event_ShowAllActionPerformed

    private void BSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSearchActionPerformed
     Connection conn;
     PreparedStatement insert;
       try
      {
      String  search = tf8.getText(); 
      String myDriver = "com.mysql.cj.jdbc.Driver";
      String myUrl = "jdbc:mysql://localhost/miliarya_lic";
      Connection con1 = DriverManager.getConnection(myUrl, "root", "BABA1137");
      insert = con1.prepareStatement("SELECT * FROM policies WHERE CONCAT(`sr_no`, `name`, `address`, `mode`) LIKE '%"+search+"%'");
      rs = insert.executeQuery();
      DefaultTableModel Df = (DefaultTableModel)databse.getModel();
      databse.setModel(DbUtils.resultSetToTableModel(rs));
      tf8.setText("");
      //System.out.println(rs);
      
      }
      catch(Exception ex)
      {
          System.out.print(ex);
      } 
      
    }//GEN-LAST:event_BSearchActionPerformed
       
        Connection conn;
        PreparedStatement insert;
        ResultSet rs;
        private void table_update()
        {
            try
       {         
       
        //System.out.print(name);
        
         String myDriver = "com.mysql.cj.jdbc.Driver";
         String myUrl = "jdbc:mysql://localhost/miliarya_lic";
         //Class.forName(myDriver);
            try ( //String sql = "insert into policies values('79','2313','Dhiraj',33,22,22.77)";
                    Connection con1 = DriverManager.getConnection(myUrl, "root", "BABA1137")) {
                insert = con1.prepareStatement("select * from policies");
                ResultSet rs = insert.executeQuery();
                ResultSetMetaData Rss = rs.getMetaData();
             var c = Rss.getColumnCount();
                    
                DefaultTableModel Df = (DefaultTableModel)databse.getModel();
                Df.setRowCount(0);
              
                while(rs.next())
                {
                    Vector v = new Vector();
                    
                    for(int a=1; a<=c; a++)
                    {
                        v.add(rs.getString("sr_no"));
                        v.add(rs.getString("policy_no"));
                        v.add(rs.getString("name"));
                        v.add(rs.getString("address"));
                        v.add(rs.getString("premium"));
                        v.add(rs.getString("datestart"));
                        v.add(rs.getString("mode"));
                       
                    }
                    Df.addRow(v);
                }
                
                //System.out.print("Addded");
               
                
                
                
            }
        
       }
       catch(HeadlessException | SQLException e)
       {
           System.out.print(e);
       }
       
    }                      
              
    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        //Date date1;
        //Date datestart1 =  (Date) tf6.getDate();
        //DateFormat dateFormat = new SimpleDateFormat("dd-mm-yyyy");
        //String datestart = (String) dateFormat.format(datestart1);
        //datestart = tf6.getDateFormatString();
        String sr_no = tf1.getText();
        String policy_no = tf2.getText();
        String name = tf3.getText();
        String address = tf4.getText();
        String premium = tf5.getText();
        String datestart =   ((JTextField)tf6.getDateEditor().getUiComponent()).getText();
        String mode = (String) tf7.getSelectedItem();
       try
       {         
       
        //System.out.print(name);
        
         //String myDriver = "com.mysql.cj.jdbc.Driver";
         String myUrl = "jdbc:mysql://localhost:3306/miliarya_lic";
         //Class.forName(myDriver);
            try (//String sql = "insert into policies values('79','2313','Dhiraj',33,22,22.77)";
                    Connection con1 = DriverManager.getConnection(myUrl, "root", "BABA1137");
                ) 
            {
                 
                if("".equals(sr_no) | "".equals(policy_no) | "".equals(name) | "".equals(address) | "".equals(premium) | "".equals(datestart) | "".equals(mode))
                {
                    JOptionPane.showMessageDialog(this,"Enter a esure Value!","WARNING",JOptionPane.WARNING_MESSAGE);
                        }
                else{
                insert = con1.prepareStatement("insert into policies(sr_no,policy_no,name,address,premium,datestart,mode)values(?,?,?,?,?,?,?)");
                System.out.print("Coonecting to Database...");
                insert.setString(1,sr_no);
                insert.setString(2,policy_no);
                insert.setString(3,name);
                insert.setString(4,address);
                insert.setString(5,premium);
                insert.setString(6,datestart);
                insert.setString(7,mode);}
                insert.executeUpdate();
                //st = conn.createStatement();
                
                //System.out.print("STMT Create");
                // note that i'm leaving "date_created" out of this insert statement
                //PreparedStatement pst = con.prepareStatement("insert into data(username,password,name,email,country,age,sex) values(?,?,?,?,?,?,?)");
                //Statement stmt = con.createStatement();
                //String myUrl = "jdbc:mysql://localhost/miliarya_lic";
                //conn = DriverManager.getConnection(myUrl, "root", "BABA1137");
                //System.out.print("Addded");
                JOptionPane.showMessageDialog(this,"Record Added");
                
                tf1.setText("");
                tf2.setText("");
                tf3.setText("");
                tf4.setText("");
                tf5.setText("");
                tf6.setDate(date);
                tf7.setSelectedItem("");
                tf1.requestFocus();
          
        table_update();
        con1.close();  
            }
       }
       catch(HeadlessException | SQLException e)
       {
           System.out.print(e);
       }
       
        
    }//GEN-LAST:event_AddActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
       
                tf1.setText("");
                tf2.setText("");
                tf3.setText("");
                tf4.setText("");
                tf5.setText("");
                tf6.setDate(date);
                tf7.setSelectedItem(0);
                tf1.requestFocus();
    }//GEN-LAST:event_UpdateActionPerformed

    private void databseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_databseMouseClicked
        //String  search = tf8.getText();
        //String myDriver = "com.mysql.cj.jdbc.Driver";
        int row = databse.getSelectedRow();
        String tc = databse.getModel().getValueAt(row, 0).toString();
        //System.out.print(tc);
        try
        {
             // String myDriver = "com.mysql.cj.jdbc.Driver";
            /*String myUrl = "jdbc:mysql://localhost/miliarya_lic";
            Connection con1 = DriverManager.getConnection(myUrl, "root", "BABA1137");
            insert = con1.prepareStatement("SELECT * FROM policies WHERE 'sr_no'="+tc+"");
                rs = insert.executeQuery();
                String sr_no = rs.getString("sr_no") ;
                String policy_no = rs.getString("policy_no") ;
                String name = rs.getString("name") ;
                String address =rs. getString("address") ;
                String premium = rs.getString("premium") ;
                String datestart =   ((JTextField)tf6.getDateEditor().getUiComponent()).getText();
                //System.out.print(datstart);
                String mode = rs.getString("mode") ;
               
                
                f1.setText(sr_no);
                tf2.setText(policy_no);
                tf3.setText(name);
                tf4.setText(address);
                tf5.setText(premium);
                ((JTextField)tf6.getDateEditor().getUiComponent()).setText(datestart);
                tf7.setSelectedItem(mode);
                */
            int value = 5;
           String d1=  ((JTextField)tf6.getDateEditor().getUiComponent()).getText();  
            DefaultTableModel Df = (DefaultTableModel)databse.getModel();
        int selecetdIndex = databse.getSelectedRow();
        tf1.setText((String) Df.getValueAt(selecetdIndex, 0));
        tf2.setText((String) Df.getValueAt(selecetdIndex, 1));
        tf3.setText((String) Df.getValueAt(selecetdIndex, 2));
        tf4.setText((String) Df.getValueAt(selecetdIndex, 3));
        tf5.setText((String) Df.getValueAt(selecetdIndex, 4));
        //Search.setText(d1);
        Date date =  (Date) tf6.getDate();
        
        
        //tf6.setText((String) Df.getValueAt(selecetdIndex, 4));
        tf7.setSelectedItem((String) Df.getValueAt(selecetdIndex, 6));
                
                //tf1.setText((String) Df.getValueAt(row, 0));
                //tf2.setText((String) Df.getValueAt(row, 1));
                //tf3.setText((String) Df.getValueAt(row, 2));
                //tf4.setText((String) Df.getValueAt(row, 3));
                //tf5.setText((String) Df.getValueAt(row, 4));
                //String date1 = Df.getString("datestart");
                //(//(JTextField)tf6.getDateEditor().getUiComponent()).setText(date);
                //tf6.setDate(date)    Df.getValueAt(selecetdIndex, 5));
                //tf7.setSelectedItem((String) Df.getValueAt(selecetdIndex, 6));
            
        }
        catch(Exception e)
        {
            System.out.print(e);
        }
        
    }//GEN-LAST:event_databseMouseClicked

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        DefaultTableModel Df = (DefaultTableModel)databse.getModel();
        int selecetdIndex = databse.getSelectedRow();  
        int id = Integer.parseInt((String) Df.getValueAt(selecetdIndex, 0));
        
        String sr_no = tf1.getText();
        String policy_no = tf2.getText();
        String name = tf3.getText();
        String address = tf4.getText();
        String premium = tf5.getText();
        String datestart =   ((JTextField)tf6.getDateEditor().getUiComponent()).getText();
        String mode = (String) tf7.getSelectedItem();
        
        try {
           
             String myDriver = "com.mysql.cj.jdbc.Driver";
             String myUrl = "jdbc:mysql://localhost:3306/miliarya_lic";
              //Class.forName("myDriver");
              Connection con1 = DriverManager.getConnection(myUrl, "root", "BABA1137");
              insert = con1.prepareStatement("UPDATE  policies set policy_no=?,name=?,address=?,premium=?,datestart=?,mode=? WHERE sr_no=?");
              
        //datestart = (String) dateFormat.format(datestart1);
                  
                
                if("".equals(sr_no) | "".equals(policy_no) | "".equals(name) | "".equals(address) | "".equals(premium) | "".equals(datestart) | "".equals(mode))
                {
                    JOptionPane.showMessageDialog(this,"Enter a esure Value!","WARNING",JOptionPane.WARNING_MESSAGE);
                        }
                else{
                insert.setString(1,policy_no);
                insert.setString(2,name);
                insert.setString(3,address);
                insert.setString(4,premium);
                insert.setString(5,datestart);
                insert.setString(6,mode);
                insert.setString(7,sr_no);
                insert.executeUpdate();
                
               JOptionPane.showMessageDialog(this,"Record Succesfully Updated");
                
                tf1.setText("");
                tf2.setText("");
                tf3.setText("");
                tf4.setText("");
                tf5.setText("");
                tf6.setDate(date);
                tf7.setSelectedItem("");
                tf1.requestFocus();
                }
            
        table_update();
        con1.close();
                
        } catch (SQLException ex) {
            Logger.getLogger(welcome_page.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_ClearActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
      
            
        DefaultTableModel Df = (DefaultTableModel)databse.getModel();
                int selecetdIndex = databse.getSelectedRow();  
            try {
                
                int id = Integer.parseInt((String) Df.getValueAt(selecetdIndex, 0));
                int dialogueResutl = JOptionPane.showConfirmDialog(this, "Do you Really want to DELETE RECORRD","Warning",JOptionPane.YES_NO_OPTION);
        
        String sr_no = tf1.getText();
      
        if(dialogueResutl == JOptionPane.YES_OPTION);
                //String myDriver = "com.mysql.cj.jdbc.Driver";
                String myUrl = "jdbc:mysql://localhost:3306/miliarya_lic?useSSL=false";
                //Class.forName("myDriver");
                Connection con1 = DriverManager.getConnection(myUrl, "root", "BABA1137");
                insert = con1.prepareStatement("DELETE  FROM policies WHERE sr_no=? ");
                
                
                insert.setString(1,sr_no);
                insert.executeUpdate();
                
               JOptionPane.showMessageDialog(this,"Record Deleted.");
                
                tf1.setText("");
                tf2.setText("");
                tf3.setText("");
                tf4.setText("");
                tf5.setText("");
                tf6.setDate(date);
                tf7.setSelectedItem(0);
                tf1.requestFocus();
                
                
                table_update(); 
                con1.close();
            } catch (SQLException ex) {
                Logger.getLogger(welcome_page.class.getName()).log(Level.SEVERE, null, ex);
            }
    
    }//GEN-LAST:event_DeleteActionPerformed

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new welcome_page().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JLabel Address;
    private javax.swing.JButton BSearch;
    private javax.swing.JButton Clear;
    private javax.swing.JLabel Date;
    private javax.swing.JButton Delete;
    private javax.swing.JLabel Header;
    private javax.swing.JLabel Header2;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JLabel Mode;
    private javax.swing.JLabel Name;
    private javax.swing.JPanel Panel2;
    private javax.swing.JLabel PolicyNo;
    private javax.swing.JLabel Premium;
    private javax.swing.JLabel Search;
    private javax.swing.JLabel SerialNo;
    private javax.swing.JButton ShowAll;
    private javax.swing.JButton Update;
    private javax.swing.JTable databse;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    private com.toedter.calendar.JDateChooser tf6;
    private javax.swing.JComboBox<String> tf7;
    private javax.swing.JTextField tf8;
    // End of variables declaration//GEN-END:variables
}
